apiVersion: apps/v1
kind: Deployment
metadata:
  name: bits
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bits
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bits
    spec:
      containers:
        - name: bits
          image: 755448775693.dkr.ecr.us-east-1.amazonaws.com/project
          imagePullPolicy: Always
          ports:
            - containerPort: 80
